flyway:
    url: jdbc:postgresql://saas-wms.clo4ugew6syl.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=s_user
    createSchemas: false
    schemas: s_user

spring:
    application:
        name: wms-user-login
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://saas-wms.clo4ugew6syl.us-east-2.rds.amazonaws.com:5432/postgres?currentSchema=s_user
        username: postgres
        password: '2kl4Gsd5c8j0Y3RW' 
    jpa:
        hibernate:
            ddl-auto: none

app:
    bi:
        topicArn: arn:aws:sns:us-east-1:719533611419:favo-wms-stg_SNS_BI
        region: us-east-1
        #accessKey: AKIA2PB4LTGNRVLMTY7C
        #secretKey: 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
    params:
        api-integration-uri: https://api-auth.mercadofavostg.com/signin

server:
    servlet:
        contextPath: /wms-user-login

logging:
    level:
        root: INFO    
        org:
            hibernate:
                type:
                    descriptor:
                        sql: FATAL

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: health,info
info:
    app:
        name: "@project.name@"
        description: "@project.description@"
        version: "@project.version@"
        encoding: "@project.build.sourceEncoding@"
        java:
            version: "@java.version@"   
        group-id: "@project.groupId@"
        artifact-id: "@project.artifactId@"
